### ISSUE TITLE
java classes not found

### ISSUE THREAD

**Issue by prakharlakshakar** [ShakilAhmedShaj/Women_Safety_Box#1]
your code is reminding me that the symbol class can not be found in it. the buid is showing me 20 errors due to this. it is also showing me that the package logger also doesn't exist.
In short 
![untitled](https://user-images.githubusercontent.com/40618882/47054672-d282f280-d1d0-11e8-968e-7494465a1ff6.png)
![untitled1](https://user-images.githubusercontent.com/40618882/47054673-d31b8900-d1d0-11e8-8302-2ca305fcaca5.jpg)

Java Complier is showing me 20 errors can you please help me in this as soon as possible please !!

**Comment by ShakilAhmedShaj** [comment]
see the commit history, and use the most earliar one
