### ISSUE TITLE
Can't find Symbol Class

### ISSUE THREAD

**Issue by ghost** [ShakilAhmedShaj/Women_Safety_Box#3]
speech/src/main/java |  
-- | --
com/sac/speech/DefaultLoggerDelegate.java |  
error: cannot find symbol class LoggerDelegate |  
error: method does not override or implement a method from a supertype |  
error: method does not override or implement a method from a supertype |  
com/sac/speech/Speech.java |  
error: cannot find symbol class SpeechDelegate |  
error: cannot find symbol class DelayedOperation |  
error: cannot find symbol class TextToSpeechCallback |  
error: cannot find symbol class SpeechRecognitionNotAvailable |  
error: cannot find symbol class SpeechRecognitionNotAvailable |  
error: cannot find symbol variable Logger |  
error: cannot find symbol variable Logger |  
error: cannot find symbol variable Logger |  
error: cannot find symbol variable Logger |  
error: cannot find symbol variable Logger |  
error: cannot find symbol class DelayedOperation |  
error: cannot find symbol variable Logger |  
error: cannot find symbol variable Logger |  
error: cannot find symbol variable Logger |  
com/sac/speech/TtsProgressListener.java |  
error: cannot find symbol class TextToSpeechCallback |  
error: cannot find symbol class TextToSpeechCallback |  
error: cannot find symbol class TextToSpeechCallback |

**Comment by ShakilAhmedShaj** [comment]
just use the initial commit version
